### ISSUE TITLE
Enforcing yoda in wordpress/recommended

### ISSUE THREAD

**Issue by inderpreet99** [ntwb/eslint-plugin-wordpress#118]
According to the [WordPress JavaScript Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#yoda-conditions), Yoda conditions are part of the best practices.

Why does `wordpress/recommended` not include yoda condition checks? It is instead part of `wordpress/jscs`. I think they belong in [wordpress](https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/blob/master/lib/configs/rules/wordpress.js) ruleset that is included in `wordpress/recommended`.

Let me know if I can send a PR for this. Thanks.

**Comment by ntwb** [comment]
@inderpreet99 Thanks for reporting this, I've updated and added this to wordpress/recommended in #119 above, and tests in https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/commit/16a13c59b0b9e02b516d6ae1da184f42adf4a391, I'll get some docs updated here soon that will make it easier for PRs to be submitted
